# Stage 1: Build Angular
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx ng build --configuration=production

# Stage 2: Serve with Nginx
FROM nginx:alpine
# Path matches dist/sitexx from angular.json
COPY --from=build /app/dist/sitexx /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
