FROM node:20-slim
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY src/ ./src
# Ensure index.js is configured for ADC and doesn't look for keys.json
ENV PORT=3001
EXPOSE 3001
CMD [ "node", "src/index.js" ]
